spring:
 application:
   name: solution
   
 datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/netcom?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul
   username: netcom
   password: 1234
   
 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
   properties:
     hibernate:
       format_sql: true
       dialect: org.hibernate.dialect.MySQLDialect
   database-platform: org.hibernate.dialect.MySQLDialect
   
 security:
   basic:
     enabled: false
     
 servlet:
   multipart:
     max-file-size: 10MB
     max-request-size: 10MB
     
 thymeleaf:
   prefix: classpath:/templates/
   suffix: .html
   cache: false

 # 정적 리소스 설정 추가
 mvc:
   static-path-pattern: /**
 web:
   resources:
     static-locations: classpath:/static/
     add-mappings: true
     chain:
       strategy:
         content:
           enabled: true
           paths: /**

server:
 port: 8080
 servlet:
   encoding:
     charset: UTF-8
     force: true

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:
    path: /v3/api-docs

logging:
 level:
   org.hibernate.SQL: debug
   org.hibernate.type: trace