spring:
 application:
   name: solution
   
 datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/netcom?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul
   username: netcom
   password: 1234

 # JPA 설정 추가
 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
   properties:
     hibernate:
       format_sql: true
       dialect: org.hibernate.dialect.MySQLDialect
   database-platform: org.hibernate.dialect.MySQLDialect

 # Security 설정 추가    
 security:
   user:
     name: netcom
     password: netcom!

 # 파일 업로드 설정
 servlet:
   multipart:
     max-file-size: 10MB
     max-request-size: 10MB

# 서버 설정
server:
 port: 8080
 servlet:
   context-path: /api
   encoding:
     charset: UTF-8
     force: true

# Swagger 설정
springdoc:
 swagger-ui:
   path: /swagger-ui.html
 api-docs:
   path: /api-docs

# 로깅 설정
logging:
 level:
   org.hibernate.SQL: debug
   org.hibernate.type: trace